# Generated by Django 5.0.2 on 2024-04-09 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviewo',
            new_name='Review',
        ),
    ]
